### ISSUE TITLE
Missing dependency 'pygtrie'

### ISSUE THREAD

**Issue by joaomdsc** [matgrioni/betacode#12]
I installed the betacode module with `pip install betacode`. Installation goes fine, but when I try to use it, it complains about a missing package 'pygtrie':

c:\a\src\py\tools\tei-xml>py tei.py 
Traceback (most recent call last):
  File "c:\a\src\py\tools\tei-xml\tei.py", line 3, in <module>
    import betacode.conv
  File "C:\Program Files\Python39\lib\site-packages\betacode\conv.py", line 4, in <module>
    import pygtrie
ModuleNotFoundError: No module named 'pygtrie'

I was expecting pip to handle this sort of thing, installing dependencies as required.

I'm running python 3.9.1 on Windows 10.

**Comment by matgrioni** [comment]
Hi joaomdsc,

Thanks for your patience and repro description. I'm planning to take a look at this this weekend. Should have a resolution for you by then.

**Comment by kristoffer-paulsson** [comment]
The same thing applies on macOs in IntelliJ IDEA:

Traceback (most recent call last):
  File "/Users/<my-self>/PycharmProjects/bible-analyzer/classics.py", line 29, in <module>
    from betacode.conv import beta_to_uni
  File "/Users/<my-self>/.local/share/virtualenvs/bible-analyzer/lib/python3.8/site-packages/betacode/conv.py", line 4, in <module>
    import pygtrie
ModuleNotFoundError: No module named 'pygtrie'

**Comment by matgrioni** [comment]
Hi @kristoffer-paulsson , thanks for resurfacing this. I clearly forgot about it. I'll take a look this weekend.

Likely I didn't properly specify dependencies. You could also get around it by installing pygtrie the same way you installed betacode.
